spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhy-dev
---
spring:
  profiles: test
  application: 
    name: microservicecloud-config-zhy-test
#请保存为UTF-8格式